export const mySkills = [
    // 'node',
    // 'express',
    // 'next',
    // 'nest',
    '.net',
    '.NET',
    'C#',
    // 'react',
    'typescript',
    'javascript',
    'backend',
    'back end',
    'back-end',
    'back - end',
    'flutter',
    'react native',
    'mobile',
    'fullstack',
    'full stack',
    'full-stack',
    'full - stack',
    // 'frontend',
    // 'front end',
    // 'front-end',
    // 'front - end',
];
